// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKcjU8oheWb1WhcKYld2-n3w5Pa8iSSqE',
    appId: '1:1083729949783:web:1abaa030ca36b94eb11f12',
    messagingSenderId: '1083729949783',
    projectId: 'flutauth-776a1',
    authDomain: 'flutauth-776a1.firebaseapp.com',
    storageBucket: 'flutauth-776a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADgB-nU3Mfdp8pITT8q0acc3svJOB69n4',
    appId: '1:1083729949783:android:9653813680312883b11f12',
    messagingSenderId: '1083729949783',
    projectId: 'flutauth-776a1',
    storageBucket: 'flutauth-776a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZe6nRY8ck8COfxFFi_-2xFiaOsbxmSIM',
    appId: '1:1083729949783:ios:794d267f55fa8225b11f12',
    messagingSenderId: '1083729949783',
    projectId: 'flutauth-776a1',
    storageBucket: 'flutauth-776a1.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZe6nRY8ck8COfxFFi_-2xFiaOsbxmSIM',
    appId: '1:1083729949783:ios:89e402ee18613055b11f12',
    messagingSenderId: '1083729949783',
    projectId: 'flutauth-776a1',
    storageBucket: 'flutauth-776a1.appspot.com',
    iosBundleId: 'com.example.auth.RunnerTests',
  );
}
